[package]
name = "critical-point-pyext"
version = "0.1.0"
edition = "2021"

[lib]
name = "critical_point_pyext"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
cirtical-point-core = { path = "../core" }
ozz-animation-rs = { path = "../../../ozz-animation-rs" }
pyo3 = "0.19"
