mod base;
mod gen_enum;
mod gen_impl;
mod gen_struct;

use anyhow::Result;
use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use std::fs::File;
use std::io::prelude::*;
use std::sync::{LazyLock, Mutex, MutexGuard};
use syn::{ItemEnum, ItemImpl, ItemStruct};

use crate::wasm::gen_enum::gen_enum;
use crate::wasm::gen_impl::gen_impl;
use crate::wasm::gen_struct::gen_struct;

pub(crate) struct WasmGenerator {
    codes: Vec<String>,
    // Store assertions for generated structs as strings
    gen_assertions: Vec<String>,
    any_failed: bool,
}

static GENERATOR: LazyLock<Mutex<WasmGenerator>> = LazyLock::new(|| Mutex::new(WasmGenerator::new()));

pub(crate) fn lock_wasm_generator() -> MutexGuard<'static, WasmGenerator> {
    match GENERATOR.lock() {
        Ok(g) => g,
        Err(_) => {
            GENERATOR.clear_poison();
            GENERATOR.lock().unwrap()
        }
    }
}

impl WasmGenerator {
    fn new() -> WasmGenerator {
        WasmGenerator {
            codes: Vec::new(),
            gen_assertions: Vec::new(),
            any_failed: false,
        }
    }

    pub(crate) fn gen_enum(&mut self, input: &ItemEnum) -> Result<()> {
        let code = gen_enum(input).map_err(|e| {
            self.any_failed = true;
            e
        })?;
        self.codes.push(code);
        Ok(())
    }

    pub(crate) fn gen_impl(&mut self, input: &ItemImpl) -> Result<()> {
        let code = gen_impl(input).map_err(|e| {
            self.any_failed = true;
            e
        })?;
        self.codes.push(code);
        Ok(())
    }

    pub(crate) fn gen_struct(&mut self, attr: TokenStream, input: &ItemStruct) -> Result<Vec<TokenStream2>> {
        let (code, rust_asserts) = gen_struct(attr, input).map_err(|e| {
            self.any_failed = true;
            e
        })?;
        self.codes.push(code);
        Ok(rust_asserts)
    }

    pub(crate) fn generate_file(&mut self) -> Result<()> {
        let mut file = File::create("./wasm-types/src/auto_gen.rs")?;

        // Write file header
        file.write_all(
            [
                "// ============================================================",
                "// This file is auto-generated by wasm_derive macro.",
                "// DO NOT EDIT MANUALLY!",
                "// ============================================================",
                "",
                "use anyhow::{Error as XError, Result as XResult};",
                "use std::fmt;",
                "use std::ops::{Add, Sub};",
                "use std::str::FromStr;",
                "",
                "use crate::error::*;",
                "use crate::consts::*;",
                "\n",
            ]
            .join("\n")
            .as_bytes(),
        )?;

        // Write all code
        for code in &self.codes {
            file.write_all(code.as_bytes())?;
        }

        // Write generated struct assertions at the end
        if !self.gen_assertions.is_empty() {
            file.write_all(b"\n// Size and alignment assertions for generated structs\n")?;
            for assertion in &self.gen_assertions {
                file.write_all(assertion.as_bytes())?;
                file.write_all(b"\n")?;
            }
        }

        match self.any_failed {
            true => Err(anyhow::anyhow!("Some errors occurred before.")),
            false => Ok(()),
        }
    }
}
