import fs from 'node:fs';
import path from 'node:path';
import { int, parseInt } from './common';
import { Resource } from './resource';
import { ID, parseID } from './common/base';

const ID_SPLIT_RE = /[\.\^]/g;

export abstract class Script {
    static #scripts = new Array<Script>();

    public readonly code: string = '';
    public readonly owner: ID = '';
    public readonly func: string = '';
    public readonly generator: Function | null = null;

    protected constructor(
        code: string | null | undefined,
        owner: ID,
        where: string,
        func: string,
        generator: Function | null = null,
    ) {
        if (code == null) {
            return;
        }
        if (typeof code !== 'string') {
            throw new Error(`${where}: must be a string`);
        }
        this.code = code;

        this.owner = parseID(owner, null, where);
        this.func = func;
        this.generator = generator;
        if (!this.generator) {
            throw new Error(`${where}: generator not found`);
        }

        Script.#scripts.push(this);
    }

    public abstract toJSON(): unknown;

    public abstract rustFuncName(): string;

    public verify(where: string) {
        if (this.code) {
            Resource.find(this.owner, where);
        }
    }

    public genFuncCode(): string {
        if (!this.code || !this.generator) {
            return '';
        }
        return this.generator(this);
    }

    public static write(project: string, folder?: string) {
        fs.mkdirSync(path.join(project, 'src'), { recursive: true });

        const codes = [
            `// ============================================================
// This file is auto-generated by turning-point.
// DO NOT EDIT MANUALLY!
// ============================================================

#![allow(unused)]

use critical_point_wasm_types::*;
use glam::*;
use glam_ext::*;`,
            ...Script.#scripts
                .filter((script) => !!script.code && !!script.generator)
                .map((script) => script.genFuncCode()),
            '',
            ScriptIf.genPredicatesCode(),
        ];
        const content = codes.join('\r\n\r\n');

        fs.writeFileSync(path.join(project, 'src', 'auto_gen.rs'), content, 'utf-8');

        const configPath = path.join(project, '.cargo', 'config.toml');
        if (folder && fs.existsSync(configPath)) {
            let config = fs.readFileSync(configPath, 'utf8');
            const keysPath = path.resolve(folder, 'key.json').split(path.sep).join('/');
            config = config.replace(/(TMPL_KEYS_PATH\s*=\s*")[^"]*(")/, `$1${keysPath}$2`);
            fs.writeFileSync(configPath, config, 'utf8');
        }

        console.log(`Scripts: ${project}`);
    }
}

export class ScriptCode extends Script {
    public constructor(
        code: string | null | undefined,
        owner: ID,
        where: string,
        opts: {
            func: string;
        },
    ) {
        const full_name = `${owner.split('.')[0]}::${opts.func}`;
        const generator = ScriptCode.#generators.get(full_name);
        super(code, owner, where, opts.func, generator);
    }

    public toJSON() {
        return !!this.code;
    }

    public rustFuncName(): string {
        return `${this.owner.replace(ID_SPLIT_RE, '_')}__${this.func}`;
    }

    static readonly #generators: ReadonlyMap<string, Function> = new Map([
        ['AiBrain::execute', ScriptCode.#genAiBrainExecute],
    ]);

    static #genAiBrainExecute(script: ScriptCode) {
        const owner = script.owner;
        const func = script.func;
        const func_name = script.rustFuncName();
        const code = script.code;
        return `
// ${owner} - ${func}
#[unsafe(no_mangle)]
pub extern "C" fn ${func_name}(
    global_ptr: *const WsGameGlobal,
    chara_ctrl_ptr: *const WsCharaControl,
    chara_phy_ptr: *const WsCharaPhysics,
    chara_val_ptr: *const WsCharaValue,
    tgt_phy_ptr: *const WsCharaPhysics,
    tgt_val_ptr: *const WsCharaValue,
    ai_tasks_ptr: *mut WsAiDo,
    ai_tasks_len: u32
) -> u64 {
    #[inline(always)]
    fn ai_brain_execute(
        global: &WsGameGlobal,
        chara_ctrl: &WsCharaControl,
        chara_physics: &WsCharaPhysics,
        chara_value: &WsCharaValue,
        target_physics: Option<&WsCharaPhysics>,
        target_value: Option<&WsCharaValue>,
        out: &mut HostBuffer<WsAiDo>
    ) -> Result<()> {
        ${code}
        Ok(())
    }
    wrap_ai_brain_execute(
        global_ptr,
        chara_ctrl_ptr,
        chara_phy_ptr,
        chara_val_ptr,
        tgt_phy_ptr,
        tgt_val_ptr,
        ai_tasks_ptr,
        ai_tasks_len,
        ai_brain_execute
    )
}`;
    }
}

export class ScriptIf extends Script {
    static #calls = new Map<string, Array<[string, 'bool' | 'result']>>();

    public readonly manager: ID;
    public readonly type: 'bool' | 'result';
    public readonly index: int = 0xffff_ffff;

    public constructor(
        code: string | null | undefined,
        owner: ID,
        manager: ID,
        where: string,
        opts: {
            func: string;
            type: 'bool' | 'result';
        },
    ) {
        const full_name = `${owner.split('.')[0]}::${opts.func}`;
        const generator = ScriptIf.#generators.get(full_name);
        super(code, owner, where, opts.func, generator);

        this.manager = manager;
        this.type = opts.type;
        if (this.code) {
            let calls = ScriptIf.#calls.get(this.manager);
            if (!calls) {
                calls = [];
                ScriptIf.#calls.set(this.manager, calls);
            }
            this.index = calls.length;
            calls.push([this.rustFuncName(), opts.type]);
        }
    }

    public override verify(where: string) {
        super.verify(where);
        if (this.code) {
            Resource.find(this.manager, where);
        }
    }

    public toJSON() {
        return this.index;
    }

    public rustFuncName(): string {
        return `${this.owner.replace(ID_SPLIT_RE, '_')}__${this.func}_${this.index}`;
    }

    static hasPredicate(manager: ID): boolean {
        return ScriptIf.#calls.has(manager);
    }

    static readonly #generators: ReadonlyMap<string, Function> = new Map([
        ['AiRoutine::if', ScriptIf.#genAiRoutineIf],
    ]);

    static #genAiRoutineIf(script: ScriptIf): string {
        const owner = script.owner;
        const func = script.func;
        const func_name = script.rustFuncName();
        const code = script.code;
        return `
// ${owner} - ${func}
#[allow(non_snake_case)]
#[inline]
pub fn ${func_name}(
    global: &WsGameGlobal,
    chara_ctrl: &WsCharaControl,
    chara_physics: &WsCharaPhysics,
    chara_value: &WsCharaValue,
    target_physics: Option<&WsCharaPhysics>,
    target_value: Option<&WsCharaValue>,
) -> ${script.type === 'bool' ? 'bool' : 'Result<bool>'} {
    ${code}
}`;
    }

    public static genPredicatesCode() {
        const code = [];
        for (const [manager, calls] of ScriptIf.#calls) {
            const case_arms = calls.map(([func_name, typ], index) => {
                const wrap_name = typ === 'bool' ? 'wrap_predicate_bool' : 'wrap_predicate_result';
                return `${index} => ${wrap_name}(global_ptr, chara_ctrl_ptr, chara_phy_ptr, chara_val_ptr, tgt_phy_ptr, tgt_val_ptr, ${func_name}),`;
            });

            const func_name = `${manager.replace(ID_SPLIT_RE, '_')}__predicates`;
            code.push(`
#[unsafe(no_mangle)]
pub extern "C" fn ${func_name}(
    global_ptr: *const WsGameGlobal,
    chara_ctrl_ptr: *const WsCharaControl,
    chara_phy_ptr: *const WsCharaPhysics,
    chara_val_ptr: *const WsCharaValue,
    tgt_phy_ptr: *const WsCharaPhysics,
    tgt_val_ptr: *const WsCharaValue,
    index: u32,
) -> u64 {
    match index as usize {
        ${case_arms.join('\r\n        ')}
        _ => (HostError::write_error(xerrf!(BadArgument; "index {}", index)), 0u32).pack(),
    }
}`);
        }
        return code.join('\r\n');
    }
}
